### ISSUE TITLE
Suggest RS-HFIQ Serial VFO Control Change

### ISSUE THREAD

**Issue by WB5KUO** [dl1ksv/rshfiq#1]
Installed this application to control RS-HFIQ with a Raspberry Pi 3 B+. Everything installed and configured correctly but the RS-HFIQ would never receive irrespective of frequency.

Solved the issue by modifying the serial control program to write the *OF2 VFO level control each time the VFO frequency is updated. No other change was made.

**Comment by dl1ksv** [comment]
Thanks for this report. If I remember well, this is not required. Once the level is set, it's kept. If you need this initialisation uncomenting should work.
https://github.com/dl1ksv/rshfiq/blob/d5d7f934a5d29a4f02a2c265cee4d8d2380b0fa1/hardware_usbserial.py#L45
should work.

**Comment by dl1ksv** [comment]
Added some clarification to README
