### ISSUE TITLE
python3 script

### ISSUE THREAD

**Issue by hc6pe** [dl1ksv/rshfiq#3]
hi 
I have a slightly different version working for me with python3, attached a copy just in case you want to compare.[https://github.com/hc6pe/rs-hfiq-hardware_usbserial/blob/main/hardware_usbserial.py](url)

**Comment by dl1ksv** [comment]
Yes, your solution is better than mine. My update is incomplete. Can you make a pr.

**Comment by hc6pe** [comment]
> Yes, your solution is better than mine. My update is incomplete. Can you make a pr.

done!

**Comment by dl1ksv** [comment]
Fixed with #4
